### ISSUE TITLE
Logout after attempting to login for too long

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#821] opened 2022-05-28 09:16 UTC
I have been waiting for multiple minutes
<img width="501" alt="image" src="https://user-images.githubusercontent.com/16632490/170819080-3f58da4e-ac7b-4326-85b7-a0d9448dbd51.png">

I would like to have the behavior back where it would reset the login after 10 seconds

**Comment by matthias-luger** [comment] 2022-06-23 12:05
@Ekwav  Is this still happening? I cant reproduce it and in theory it should reset after 15 second.
![image](https://user-images.githubusercontent.com/58751503/175294626-cb24d820-6e1a-467e-96cb-adc70853e9a7.png)

**Comment by Ekwav** [comment] 2022-06-29 17:18
> @Ekwav Is this still happening? I cant reproduce it and in theory it should reset after 15 second. ![image](https://user-images.githubusercontent.com/58751503/175294626-cb24d820-6e1a-467e-96cb-adc70853e9a7.png)

Yes this still happens. I was able to replicate it again. (went to google.com and logged out) did not stop after 15 seconds

**Comment by matthias-luger** [comment] 2022-09-13 22:19
Should be fixed with https://github.com/Coflnet/hypixel-react/pull/899

**Closed as completed by matthias-luger** 2022-09-13 22:19 UTC
Labels: bug, invalid
