### ISSUE TITLE
Add mayors to the all time chart

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#694] opened 2022-02-21 20:53 UTC
It could be useful to overlay the hypixel mayors over the all time graph to see correlations.
Suggestion discussion https://discord.com/channels/267680588666896385/945314457674997770/945422189698613329

**Comment by matthias-luger** [comment] 2022-05-10 03:03
waits for #787 to be fixed

**Comment by matthias-luger** [comment] 2022-09-20 02:22
duplicate of #874

**Closed as completed by matthias-luger** 2022-09-20 02:22 UTC
Labels: enhancement
